# Generated by Django 3.2.8 on 2021-11-05 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('social_number', models.CharField(blank=True, max_length=50, null=True)),
                ('short_intro', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=200)),
                ('profile_image', models.ImageField(blank=True, default='profiles/users-default.png', null=True, upload_to='profiles/')),
                ('social_facebook', models.CharField(blank=True, max_length=50, null=True)),
                ('social_instagram', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
